baseURL = "https://davidkroell.com"
title = "David Kröll"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "David Kröll"
  useMDAbout = true
  avatarURL = "/images/avatar.jpg"
  avatarAltText = "Picture of me"
  avatarSize = "size-l"
  customHeadHTML = """
    <script defer type="module">
      import flamethrower from '/js/flamethrower-router0.0.0-meme.12.mjs';
      flamethrower({ prefetch: 'visible' });
    </script>

    <!-- install flamethrower event listener to the ready function defined in main.js -->
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        window.addEventListener('flamethrower:router:end', ready);
      });
    </script>
  """
  socialIcons = [
    {name = "github", url = "https://github.com/davidkroell"},
    {name = "linkedin", url = "https://linkedin.com/in/davidkroell"},
    {name = "instagram", url = "https://instagram.com/david1kroell"},
  ]
  metaKeywords = ["david", "kroell", "blog", "personal", "homepage", "open source", "software", "engineering", "developer", "student", "TU", "Graz", "IT", "expert", "linux", "golang"]
  metaDescription = """
    My name is David, and I work as a software engineer in the Austrian city of Graz.
    I'm currently enrolled in TU Graz's Software Engineering & Management programme.
    In addition, I work as a Golang Engineer at Anexia.
  """

[menu]
  [[menu.main]]
    name = "home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "posts"
    pre = "<span data-feather='feather'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "books"
    pre = "<span data-feather='book'></span>"
    url = "/books/"
    weight = 3

  [[menu.main]]
    name = "tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/davidkroell/davidkroell.com"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
